


import QuienEsQuien.Jugador;
import QuienEsQuien.Personajes;
import QuienEsQuien.ReproductorMusica;
import java.awt.Font;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSlider;
import javax.swing.Timer;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author David
 */
public class PantallaJuego extends javax.swing.JFrame {
    ReproductorMusica music = new ReproductorMusica();
    private int tiempoTranscurrido, segundos, minutos;
    private Font font = new Font("DialogInput", Font.PLAIN, 30);
    private File archivo = new File("jugadores.dat");
    private int puntuacion;
    private String answer;
    private List<JLabel> labels = new ArrayList<>();
    private Personajes personajeElegido = Personajes.mostrarSolucion();
    private Timer timer;
    private boolean musicOn = false;
    private int volumenActual = 100;

   
    public PantallaJuego() {
        
        initComponents();
        music.playAudio("src/songs/juego.wav");
        musicOn = true;
        pPreguntas.setVisible(false);
        lTimer.setText("00:00");
        lTimer.setFont(font);
        timer = new Timer(1000, e -> {
            tiempoTranscurrido++;
            segundos = tiempoTranscurrido % 60;
            minutos = tiempoTranscurrido / 60;
            lTimer.setText(String.format("%02d:%02d", minutos, segundos));
        });
        timer.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lPers1 = new javax.swing.JLabel();
        lPers4 = new javax.swing.JLabel();
        lPers12 = new javax.swing.JLabel();
        lPers5 = new javax.swing.JLabel();
        lPers6 = new javax.swing.JLabel();
        lPers11 = new javax.swing.JLabel();
        lPers9 = new javax.swing.JLabel();
        lPers10 = new javax.swing.JLabel();
        lPers7 = new javax.swing.JLabel();
        lPers8 = new javax.swing.JLabel();
        lPers13 = new javax.swing.JLabel();
        lPers0 = new javax.swing.JLabel();
        lPers2 = new javax.swing.JLabel();
        lPers3 = new javax.swing.JLabel();
        lPers14 = new javax.swing.JLabel();
        lPers15 = new javax.swing.JLabel();
        pAnswers = new javax.swing.JPanel();
        lQuestion0 = new javax.swing.JLabel();
        lAnswer0 = new javax.swing.JLabel();
        pPreguntas = new javax.swing.JPanel();
        bPregunt0 = new javax.swing.JButton();
        bPregunt1 = new javax.swing.JButton();
        bPregunt2 = new javax.swing.JButton();
        bPregunt3 = new javax.swing.JButton();
        bPregunt4 = new javax.swing.JButton();
        bPregunt6 = new javax.swing.JButton();
        bPregunt7 = new javax.swing.JButton();
        bPregunt8 = new javax.swing.JButton();
        pButtons = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        bQuestion = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        bResolve = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        bSurrender = new javax.swing.JButton();
        pTimer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lTimer = new javax.swing.JLabel();
        pMusic = new javax.swing.JPanel();
        bPlay = new javax.swing.JButton();
        bPause = new javax.swing.JButton();
        sVolum = new javax.swing.JSlider();
        mbMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mInstructions = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));

        jScrollPane1.setBackground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(51, 51, 51));
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 100));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0};
        jPanel2Layout.rowHeights = new int[] {0};
        jPanel2Layout.columnWeights = new double[] {1.0};
        jPanel2Layout.rowWeights = new double[] {1.0};
        jPanel2.setLayout(jPanel2Layout);

        lPers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Avallac.png"))); // NOI18N
        lPers1.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers1.setMinimumSize(new java.awt.Dimension(80, 80));
        lPers1.setPreferredSize(new java.awt.Dimension(100, 100));
        lPers1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers1MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers1, gridBagConstraints);

        lPers4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Eskel.png"))); // NOI18N
        lPers4.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers4.setMinimumSize(new java.awt.Dimension(100, 100));
        lPers4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers4MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers4, gridBagConstraints);

        lPers12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Hjalmar.png"))); // NOI18N
        lPers12.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers12MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers12, gridBagConstraints);

        lPers5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Keira.png"))); // NOI18N
        lPers5.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers5MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers5, gridBagConstraints);

        lPers6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Fringilla.png"))); // NOI18N
        lPers6.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers6MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers6, gridBagConstraints);

        lPers11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Shani.png"))); // NOI18N
        lPers11.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers11MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers11, gridBagConstraints);

        lPers9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Geralt.png"))); // NOI18N
        lPers9.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers9MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers9, gridBagConstraints);

        lPers10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Triss.png"))); // NOI18N
        lPers10.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers10MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers10, gridBagConstraints);

        lPers7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Lambert.png"))); // NOI18N
        lPers7.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers7MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers7, gridBagConstraints);

        lPers8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Jaskier.png"))); // NOI18N
        lPers8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers8MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers8, gridBagConstraints);

        lPers13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Vesemir.png"))); // NOI18N
        lPers13.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers13MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers13, gridBagConstraints);

        lPers0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Cerys.png"))); // NOI18N
        lPers0.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers0.setPreferredSize(new java.awt.Dimension(152, 158));
        lPers0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers0MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers0, gridBagConstraints);

        lPers2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Cirilla.png"))); // NOI18N
        lPers2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers2, gridBagConstraints);

        lPers3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Emhyr.png"))); // NOI18N
        lPers3.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers3MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers3, gridBagConstraints);

        lPers14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Von everec.png"))); // NOI18N
        lPers14.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers14MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers14, gridBagConstraints);

        lPers15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/Yennefer.png"))); // NOI18N
        lPers15.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        lPers15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lPers15MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel2.add(lPers15, gridBagConstraints);

        jPanel6.add(jPanel2);

        pAnswers.setBackground(new java.awt.Color(51, 51, 51));
        pAnswers.setLayout(new java.awt.GridLayout(2, 0));

        lQuestion0.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        lQuestion0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lQuestion0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pAnswers.add(lQuestion0);

        lAnswer0.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        lAnswer0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAnswer0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pAnswers.add(lAnswer0);

        pPreguntas.setBackground(new java.awt.Color(51, 51, 51));
        pPreguntas.setLayout(new java.awt.GridLayout(8, 0, 0, 10));

        bPregunt0.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt0.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt0.setText("Has white hair?");
        bPregunt0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt0MouseClicked(evt);
            }
        });
        bPregunt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunt0ActionPerformed(evt);
            }
        });
        pPreguntas.add(bPregunt0);

        bPregunt1.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt1.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt1.setText("Has brown or black hair?");
        bPregunt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt1MouseClicked(evt);
            }
        });
        bPregunt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunt1ActionPerformed(evt);
            }
        });
        pPreguntas.add(bPregunt1);

        bPregunt2.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt2.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt2.setText("Has red hair?");
        bPregunt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt2MouseClicked(evt);
            }
        });
        pPreguntas.add(bPregunt2);

        bPregunt3.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt3.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt3.setText("Has scars?");
        bPregunt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt3MouseClicked(evt);
            }
        });
        pPreguntas.add(bPregunt3);

        bPregunt4.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt4.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt4.setText("Has long hair?");
        bPregunt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt4MouseClicked(evt);
            }
        });
        bPregunt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPregunt4ActionPerformed(evt);
            }
        });
        pPreguntas.add(bPregunt4);

        bPregunt6.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt6.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt6.setText("Has a full beard?");
        bPregunt6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt6MouseClicked(evt);
            }
        });
        pPreguntas.add(bPregunt6);

        bPregunt7.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt7.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt7.setText("Is it a female character?");
        bPregunt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt7MouseClicked(evt);
            }
        });
        pPreguntas.add(bPregunt7);

        bPregunt8.setBackground(new java.awt.Color(77, 77, 77));
        bPregunt8.setFont(new java.awt.Font("DialogInput", 1, 16)); // NOI18N
        bPregunt8.setText("Has only a mustache and goatee?");
        bPregunt8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPregunt8MouseClicked(evt);
            }
        });
        pPreguntas.add(bPregunt8);

        pButtons.setBackground(new java.awt.Color(51, 51, 51));
        pButtons.setLayout(new java.awt.GridLayout(3, 0));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setPreferredSize(new java.awt.Dimension(102, 38));

        bQuestion.setBackground(new java.awt.Color(77, 77, 77));
        bQuestion.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bQuestion.setText("Question");
        bQuestion.setPreferredSize(new java.awt.Dimension(129, 41));
        bQuestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bQuestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bQuestionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bQuestionMouseExited(evt);
            }
        });
        bQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuestionActionPerformed(evt);
            }
        });
        jPanel9.add(bQuestion);

        pButtons.add(jPanel9);

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));

        bResolve.setBackground(new java.awt.Color(77, 77, 77));
        bResolve.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bResolve.setText("Resolve");
        bResolve.setPreferredSize(new java.awt.Dimension(129, 41));
        bResolve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bResolveMouseClicked(evt);
            }
        });
        bResolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResolveActionPerformed(evt);
            }
        });
        jPanel7.add(bResolve);

        pButtons.add(jPanel7);

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(94, 38));

        bSurrender.setBackground(new java.awt.Color(77, 77, 77));
        bSurrender.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        bSurrender.setText("Surrender");
        bSurrender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bSurrenderMouseClicked(evt);
            }
        });
        jPanel8.add(bSurrender);

        pButtons.add(jPanel8);

        pTimer.setBackground(new java.awt.Color(51, 51, 51));
        pTimer.setLayout(new java.awt.GridLayout(2, 0));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TIMER");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pTimer.add(jLabel1);

        lTimer.setBackground(new java.awt.Color(51, 51, 51));
        lTimer.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lTimer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pTimer.add(lTimer);

        pMusic.setBackground(new java.awt.Color(51, 51, 51));
        pMusic.setLayout(new java.awt.GridBagLayout());

        bPlay.setBackground(new java.awt.Color(51, 51, 51));
        bPlay.setForeground(new java.awt.Color(51, 51, 51));
        bPlay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/play.png"))); // NOI18N
        bPlay.setAlignmentY(0.0F);
        bPlay.setBorder(null);
        bPlay.setIconTextGap(0);
        bPlay.setMargin(new java.awt.Insets(0, 0, 0, 0));
        bPlay.setMinimumSize(new java.awt.Dimension(10, 10));
        bPlay.setName(""); // NOI18N
        bPlay.setPreferredSize(new java.awt.Dimension(28, 25));
        bPlay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPlayMouseClicked(evt);
            }
        });
        pMusic.add(bPlay, new java.awt.GridBagConstraints());

        bPause.setBackground(new java.awt.Color(51, 51, 51));
        bPause.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bPause.setForeground(new java.awt.Color(51, 51, 51));
        bPause.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/pause.png"))); // NOI18N
        bPause.setAlignmentY(0.0F);
        bPause.setBorder(null);
        bPause.setBorderPainted(false);
        bPause.setName(""); // NOI18N
        bPause.setPreferredSize(new java.awt.Dimension(28, 25));
        bPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPauseMouseClicked(evt);
            }
        });
        pMusic.add(bPause, new java.awt.GridBagConstraints());

        sVolum.setBackground(new java.awt.Color(51, 51, 51));
        sVolum.setMajorTickSpacing(10);
        sVolum.setMinimum(1);
        sVolum.setMinorTickSpacing(1);
        sVolum.setToolTipText("");
        sVolum.setValue(100);
        sVolum.setPreferredSize(new java.awt.Dimension(100, 16));
        sVolum.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sVolumStateChanged(evt);
            }
        });
        pMusic.add(sVolum, new java.awt.GridBagConstraints());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
                    .addComponent(pAnswers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 3, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pTimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(pMusic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(pAnswers, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mbMenu.setBackground(new java.awt.Color(77, 77, 77));
        mbMenu.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(77, 77, 77));
        jMenu1.setText("Start");
        jMenu1.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jMenu1MouseExited(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        mbMenu.add(jMenu1);

        mInstructions.setBackground(new java.awt.Color(77, 77, 77));
        mInstructions.setText("Instruction");
        mInstructions.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        mInstructions.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mInstructions.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mInstructions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mInstructionsMouseClicked(evt);
            }
        });
        mbMenu.add(mInstructions);

        jMenu3.setBackground(new java.awt.Color(77, 77, 77));
        jMenu3.setText("Scores");
        jMenu3.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        mbMenu.add(jMenu3);

        jMenu2.setBackground(new java.awt.Color(77, 77, 77));
        jMenu2.setText("Exit");
        jMenu2.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        mbMenu.add(jMenu2);

        setJMenuBar(mbMenu);

        setBounds(0, 0, 1234, 1035);
    }// </editor-fold>//GEN-END:initComponents

    private void bQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuestionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bQuestionActionPerformed

    private void lPers1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers1MouseClicked
        lPers1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers1MouseClicked

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed


    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

        
        int option = JOptionPane.showConfirmDialog(this, "\"Are you sure you want to return to the main menu?\"", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            music.stopAudio("src/songs/juego.wav");
            musicOn = false;
            PantallaPrincipal pantallaprincipal = new PantallaPrincipal();
            this.setVisible(false);
            pantallaprincipal.setVisible(true);
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseEntered

    }//GEN-LAST:event_jMenu1MouseEntered

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        int option = JOptionPane.showConfirmDialog(this, "\"Are you sure you want to get out of the game?\"", "Confirmación", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "\"Thanks for playing, see you soon!\"");
            System.exit(0);
        }

    }//GEN-LAST:event_jMenu2MouseClicked

    private void lPers6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers6MouseClicked
        lPers6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers6MouseClicked

    private void lPers7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers7MouseClicked
        lPers7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers7MouseClicked

    private void lPers8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers8MouseClicked
        lPers8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers8MouseClicked

    private void lPers11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers11MouseClicked
        lPers11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers11MouseClicked

    private void lPers4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers4MouseClicked
        lPers4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers4MouseClicked

    private void lPers10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers10MouseClicked
        lPers10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers10MouseClicked

    private void lPers9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers9MouseClicked
        lPers9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers9MouseClicked

    private void lPers13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers13MouseClicked
        lPers13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers13MouseClicked

    private void lPers12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers12MouseClicked
        lPers12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers12MouseClicked

    private void lPers15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers15MouseClicked
        lPers15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers15MouseClicked

    private void lPers14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers14MouseClicked
        lPers14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers14MouseClicked

    private void lPers0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers0MouseClicked
        lPers0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers0MouseClicked

    private void lPers2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers2MouseClicked
        lPers2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers2MouseClicked

    private void lPers3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers3MouseClicked
        lPers3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers3MouseClicked

    private void lPers5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lPers5MouseClicked
        lPers5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imágenes/tachada.jpg")));
    }//GEN-LAST:event_lPers5MouseClicked

    private void bPregunt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunt0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPregunt0ActionPerformed

    private void bPregunt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPregunt1ActionPerformed

    private void bPregunt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPregunt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bPregunt4ActionPerformed

    private void bQuestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bQuestionMouseClicked
        pPreguntas.setVisible(true);
    }//GEN-LAST:event_bQuestionMouseClicked

    private void bPregunt0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt0MouseClicked
        puntuacion += 5;
        lQuestion0.setText(bPregunt0.getText());
        if (personajeElegido.getColorPelo().equalsIgnoreCase("blanco")) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        bPregunt0.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt0MouseClicked

    private void bPregunt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt1MouseClicked
        lQuestion0.setText(bPregunt1.getText());
        if (personajeElegido.getColorPelo().equalsIgnoreCase("moreno")) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt1.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt1MouseClicked

    private void bPregunt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt2MouseClicked
        lQuestion0.setText(bPregunt2.getText());
        if (personajeElegido.getColorPelo().equalsIgnoreCase("pelirrojo")) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt2.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt2MouseClicked

    private void bPregunt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt3MouseClicked
        lQuestion0.setText(bPregunt3.getText());
        if (personajeElegido.isCicatrices()) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt3.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt3MouseClicked

    private void bPregunt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt4MouseClicked
        lQuestion0.setText(bPregunt4.getText());
        if (personajeElegido.isPeloLargo()) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt4.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt4MouseClicked

    private void bPregunt6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt6MouseClicked
        lQuestion0.setText(bPregunt6.getText());
        if (personajeElegido.isBarba()) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt6.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt6MouseClicked

    private void bPregunt7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt7MouseClicked
        lQuestion0.setText(bPregunt7.getText());
        if (personajeElegido.getGenero().equalsIgnoreCase("Mujer")) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt7.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt7MouseClicked

    private void bPregunt8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPregunt8MouseClicked
        lQuestion0.setText(bPregunt8.getText());
        if (personajeElegido.isBigote()) {
            lAnswer0.setText("Yes");
        } else {
            lAnswer0.setText("No");
        }
        puntuacion += 5;
        bPregunt8.setVisible(false);
        pPreguntas.setVisible(false);
    }//GEN-LAST:event_bPregunt8MouseClicked

    private void bSurrenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSurrenderMouseClicked
        
        int option = JOptionPane.showConfirmDialog(this, "\"Are you sure you want to give up?\"", "Confirmación", JOptionPane.YES_NO_CANCEL_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "The correct answer was: " + " " + personajeElegido.getNombre());
            music.stopAudio("src/songs/juego.wav");
            musicOn = false;
            this.dispose();
            PantallaPrincipal pantallaprincipal = new PantallaPrincipal();
            pantallaprincipal.setVisible(true);
        } else {
            
        }
    }//GEN-LAST:event_bSurrenderMouseClicked

    private void bResolveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bResolveMouseClicked
        
        timer.stop();
        puntuacion += tiempoTranscurrido / 5;
        
        answer = JOptionPane.showInputDialog(this, "Enter the name of the character: ");   
        if (answer != null) {
            if (answer.equalsIgnoreCase(personajeElegido.getNombre())) {
            JOptionPane.showMessageDialog(this, "Congratulations you are right!! \n"
                    + " Your puntuation is " + puntuacion);
            Jugador.guardarPuntuaciones("jugadores.dat", puntuacion);
            music.stopAudio("src/songs/juego.wav");
            musicOn = false;
            PantallaPrincipal pantallaprincipal = new PantallaPrincipal();
            pantallaprincipal.setVisible(true);
            this.dispose();
        } else  {
            puntuacion += 10;
            JOptionPane.showMessageDialog(this, "The answer is not correct, continue playing..");
            timer.start();
        }
        } else {
            puntuacion += 10;
            JOptionPane.showMessageDialog(this, "The answer is not correct, continue playing..");
            timer.start();
        }
        
    }//GEN-LAST:event_bResolveMouseClicked

    private void jMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseExited

    }//GEN-LAST:event_jMenu1MouseExited

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        Puntuaciones puntuaciones = new Puntuaciones();
        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, "\"There are no saved scores yet, play a game.\"");
        } else {

            puntuaciones.setVisible(true);
        }

    }//GEN-LAST:event_jMenu3MouseClicked

    private void bQuestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bQuestionMouseEntered
    
    }//GEN-LAST:event_bQuestionMouseEntered

    private void bQuestionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bQuestionMouseExited

    }//GEN-LAST:event_bQuestionMouseExited

    private void mInstructionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mInstructionsMouseClicked
        Instructions instructions = new Instructions();
        instructions.setVisible(true);
    }//GEN-LAST:event_mInstructionsMouseClicked

    private void bResolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResolveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bResolveActionPerformed

    private void bPlayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPlayMouseClicked
        if (!musicOn) {
            music.playAudio("src/songs/juego.wav");
            music.setVolumen(volumenActual);
            musicOn = true;
        }
       
    }//GEN-LAST:event_bPlayMouseClicked

    private void bPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPauseMouseClicked

        music.stopAudio("src/songs/juego.wav");
        musicOn = false;
    }//GEN-LAST:event_bPauseMouseClicked

    private void sVolumStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sVolumStateChanged
        if (musicOn) {
            JSlider source = (JSlider) evt.getSource();
            volumenActual =  source.getValue();
            music.setVolumen( volumenActual);
        }

    }//GEN-LAST:event_sVolumStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bPause;
    private javax.swing.JButton bPlay;
    private javax.swing.JButton bPregunt0;
    private javax.swing.JButton bPregunt1;
    private javax.swing.JButton bPregunt2;
    private javax.swing.JButton bPregunt3;
    private javax.swing.JButton bPregunt4;
    private javax.swing.JButton bPregunt6;
    private javax.swing.JButton bPregunt7;
    private javax.swing.JButton bPregunt8;
    private javax.swing.JButton bQuestion;
    private javax.swing.JButton bResolve;
    private javax.swing.JButton bSurrender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAnswer0;
    private javax.swing.JLabel lPers0;
    private javax.swing.JLabel lPers1;
    private javax.swing.JLabel lPers10;
    private javax.swing.JLabel lPers11;
    private javax.swing.JLabel lPers12;
    private javax.swing.JLabel lPers13;
    private javax.swing.JLabel lPers14;
    private javax.swing.JLabel lPers15;
    private javax.swing.JLabel lPers2;
    private javax.swing.JLabel lPers3;
    private javax.swing.JLabel lPers4;
    private javax.swing.JLabel lPers5;
    private javax.swing.JLabel lPers6;
    private javax.swing.JLabel lPers7;
    private javax.swing.JLabel lPers8;
    private javax.swing.JLabel lPers9;
    private javax.swing.JLabel lQuestion0;
    private javax.swing.JLabel lTimer;
    private javax.swing.JMenu mInstructions;
    private javax.swing.JMenuBar mbMenu;
    private javax.swing.JPanel pAnswers;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pMusic;
    private javax.swing.JPanel pPreguntas;
    private javax.swing.JPanel pTimer;
    private javax.swing.JSlider sVolum;
    // End of variables declaration//GEN-END:variables

}
