

import QuienEsQuien.Jugador;
import java.awt.Color;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author David
 */
public class Puntuaciones extends javax.swing.JFrame {
    File archivo = new File("jugadores.dat");
    List <JLabel> labels = new ArrayList<>();
    
 
    /**
     * Creates new form Puntuaciones
     */
    public Puntuaciones() {
        
        initComponents();   
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         labels.add(lPunt0);
         labels.add(lPunt1);
         labels.add(lPunt2);
         labels.add(lPunt3);
         labels.add(lPunt4);
         labels.add(lPunt5);
         labels.add(lPunt6);
         labels.add(lPunt7);
         labels.add(lPunt8);
         labels.add(lPunt9); 
         for( JLabel label : labels) {
             label.setForeground(Color.red);
         }
        Jugador.mostrarPuntuaciones("jugadores.dat", labels );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lPunt0 = new javax.swing.JLabel();
        lPunt1 = new javax.swing.JLabel();
        lPunt2 = new javax.swing.JLabel();
        lPunt3 = new javax.swing.JLabel();
        lPunt4 = new javax.swing.JLabel();
        lPunt5 = new javax.swing.JLabel();
        lPunt6 = new javax.swing.JLabel();
        lPunt7 = new javax.swing.JLabel();
        lPunt8 = new javax.swing.JLabel();
        lPunt9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(150, 525));
        jPanel2.setLayout(new java.awt.GridLayout(11, 1, 0, 25));

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SCORES");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel1);

        lPunt0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt0);

        lPunt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt1);

        lPunt2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt2);

        lPunt3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt3);

        lPunt4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt4);

        lPunt5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt5);

        lPunt6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt6);

        lPunt7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt7);

        lPunt8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt8);

        lPunt9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lPunt9);

        jPanel1.add(jPanel2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Puntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Puntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Puntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Puntuaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Puntuaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lPunt0;
    private javax.swing.JLabel lPunt1;
    private javax.swing.JLabel lPunt2;
    private javax.swing.JLabel lPunt3;
    private javax.swing.JLabel lPunt4;
    private javax.swing.JLabel lPunt5;
    private javax.swing.JLabel lPunt6;
    private javax.swing.JLabel lPunt7;
    private javax.swing.JLabel lPunt8;
    private javax.swing.JLabel lPunt9;
    // End of variables declaration//GEN-END:variables
}

